version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urluser -d urlshortener"]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_DSN: "postgres://urluser:urlpass@db:5432/urlshortener?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      ADMIN_TOKEN: "change-me"
      DEV_HTTP: "true"
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sleep 5 && /app"] # Optional: adds a small delay before starting
